server:
  persistentVolume:
    enabled: true
    size: 10Gi
  retention: 15d
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  service:
    type: LoadBalancer
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/load-balancer-source-ranges: '["74.12.8.53/32"]'

alertmanager:
  enabled: false

pushgateway:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

# Global service configuration is not used for server component
service:
  type: ClusterIP

# Remove ingress configuration since we're using LoadBalancer service type 