apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 800
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: otel
        send_timestamps: true
        metric_expiration: 180m
      logging:
        loglevel: debug
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [prometheus, logging]
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [logging] 